### ISSUE TITLE
SeqAn3 ICE

### ISSUE THREAD

**Issue by h-2** [saarraz/clang-concepts-old#12]
We have rather large highly concept-ualised codebase and have just begun testing your branch. First of all, thanks a lot for this important work!

This is the first ICE we are seeing:
[alphabet_test-c3cc43.cpp.gz](https://github.com/saarraz/clang-concepts/files/2331924/alphabet_test-c3cc43.cpp.gz)
[alphabet_test-c3cc43.sh.gz](https://github.com/saarraz/clang-concepts/files/2331925/alphabet_test-c3cc43.sh.gz)

**Comment by h-2** [comment]
An updated version where the (unrelated) errors are fixed:
[alphabet_test-86f363.cpp.gz](https://github.com/saarraz/clang-concepts/files/2331946/alphabet_test-86f363.cpp.gz)
[alphabet_test-86f363.sh.gz](https://github.com/saarraz/clang-concepts/files/2331947/alphabet_test-86f363.sh.gz)

**Comment by marehr** [comment]
I used creduce and it gave me this reduced example:

```c++
template <typename f> using g = f;
template <typename c> concept e = requires(c d){{d}->g<c>;};
struct {
  template <typename a> requires e<a> operator a();
} b{b};
```

**Comment by saarraz** [comment]
marehr's example doesn't seem to produce an ICE https://godbolt.org/z/rz9QL9

**Comment by h-2** [comment]
@saarraz It does if one increases maximum template-depth to e.g. 2048 which I also did. But I don't know why one would have for this example.

**Comment by marehr** [comment]
Okay, I will report the next errors that we find via godbolt https://godbolt.org/z/ME5abo xD

**Comment by h-2** [comment]
Any news here? Something we can do to help fix this?

Thank you very much!

**Comment by saarraz** [comment]
Hey, sorry but I haven't had the time to work on this for the past couple weeks, I have a paper submission soon. Once I'm done with that I'll be back on this full speed.

**Comment by h-2** [comment]
No problem, and thanks!

**Comment by h-2** [comment]
*polite ping*

Anything we can do to help?

**Comment by saarraz** [comment]
Hi - so sorry for taking so long to address this, I've had a real busy month.
Anyway, I managed to narrow down your issue further, and it turns out to be an issue with clang in general, unrelated to concepts: https://godbolt.org/z/qfmUnT
When template-depth is too high, a stack overflow occurs and the compiler crashes.
I assume the best way to handle this would be to emit a diagnostic if stack space is insufficient to process the given recursive template, but anyway this is outside the scope of this patch - could you submit this as a separate bug report to clang?

**Comment by marehr** [comment]
But our question is why the template-depth is too high in this particular case?

The statements seem so simple to me that I don't understand why there is a template depth of more than 1024 needed.

**Comment by saarraz** [comment]
Your code, as I understand it, has an endless template recursion - you say that the operator to convert the type to itself is valid only if the type is convertible to itself, which in turn tries to instantiate the operator

**Comment by marehr** [comment]
No, because

```c++
template <typename f> using g = f;
template <typename c> concept e = requires(c d){{d}->g<c>;};
struct {
  template <typename a> requires e<a> operator a();
} b{b};
```

fails (note that g is just the identity), but

```c++
template <typename c> concept e = requires(c d){{d}->c;};
struct {
  template <typename a> requires e<a> operator a();
} b{b};
```
https://godbolt.org/z/00sJqy

does not.

**Comment by saarraz** [comment]
This is because I have an if that skips the implicit conversion if the type you're trying to convert to is the same type of the expression.
A quick reading of the standard indicates that I may not be allowed to have that if (if this is indeed the case, I'll remove it), but even if I remove that if, your second example would behave similar to the first one and you'd still get the ICE

**Comment by saarraz** [comment]
OK, the aforementioned if was indeed non-conforming, and I removed it - your two examples should now behave the same (after godbolt updates), and both invoke the conversion which in your case leads to an infinite template recursion.

**Comment by marehr** [comment]
Okay, so this is a gcc bug? Because it should also have an infinite loop.

**Comment by saarraz** [comment]
A recursive template instantiation is undefined behavior so gcc isn't required to behave in a certain way.
