### ISSUE TITLE
ICE when compiling a (not-yet-complete) migration of cmcstl2

### ISSUE THREAD

**Issue by cjdb** [saarraz/clang-concepts-old#2]
I tried starting to port cmcstl2 to Clang this afternoon, and ran into this ICE pretty early on.

Due to the way GitHub lets me upload files, I've had to suffix both with `.txt`.
[core-be3a84.cpp.txt](https://github.com/saarraz/clang-concepts/files/2266987/core-be3a84.cpp.txt)
[core-be3a84.sh.txt](https://github.com/saarraz/clang-concepts/files/2266992/core-be3a84.sh.txt)

**Comment by saarraz** [comment]
hey, thanks very much for the report.
I've found and fixed a couple of bugs, now the ICEs are gone (there is still an ICE received when the error count reaches the limit, but that seems like an error in another part of clang that may have already been fixed in a more recent version of clang than the one I'm merged against. to bypass this, compile with -ferror-limit=0).

See if the errors make sense now.
Also, could you link me to the repo of your port?

**Comment by cjdb** [comment]
Here's a very crude port; I plan to use the diagnostics to find the nooks and crannies: https://github.com/cjdb/cmcstl2/tree/clang-concepts

**Comment by saarraz** [comment]
What was the status with this again?

**Comment by saarraz** [comment]
ICE seems to be gone
