### ISSUE TITLE
Normalization of constraints

### ISSUE THREAD

**Issue by marehr** [saarraz/clang-concepts-old#23]
Hi saarraz,

can you take a look at this? All of the following works with gcc, but only the not-commented out parts work with clang.

```c++
template <typename>
struct value_type;

template <typename t>
using value_type_t = typename value_type<t>::type;

template <typename value_t, unsigned size>
struct value_type<value_t[size]>
{
    using type = value_t;
};

template <typename t>
constexpr unsigned dimension_v = 0;

template <typename t>
concept has_value_type = requires (t) { typename value_type_t<t>; };

template <typename t>
concept has_value_value_type = requires (t) { typename value_type_t<value_type_t<t>>; };

template <typename t>
     // requires requires (t) { typename value_type_t<t>; } // does not work
     requires has_value_type<t> // works
constexpr unsigned dimension_v<t> = 1;

template <typename t>
    // requires requires (t)
    // {
    //     typename value_type_t<t>;
    //     typename value_type_t<value_type_t<t>>;
    // } // does not work
    // requires requires (t)
    // {
    //     requires has_value_type<t>;
    //     typename value_type_t<value_type_t<t>>;
    // } // does not work
    requires has_value_type<t> && has_value_value_type<t> // works
constexpr unsigned dimension_v<t> = dimension_v<value_type_t<t>> + 1;

static_assert(dimension_v<int> == 0);
static_assert(dimension_v<int[1]> == 1);
static_assert(dimension_v<int[1][1]> == 2);
static_assert(dimension_v<int[1][1][1]> == 3);

int main() {return 0;}
```

According to https://en.cppreference.com/w/cpp/language/constraints#Partial_ordering_of_constraints:

> Before any further analysis, constraints are normalized by substituting the body of every name concept and every requires expression until what is left is a sequence of conjunctions and disjunctions on atomic constraints.

I think every version should work.

**Comment by saarraz** [comment]
Your example does not work for several reasons:
Note that constraint expressions that are similarly typed do not subsume each other:
```
template<typename T> requires sizeof(T) >= 2
int foo() { }
template<typename T> requires sizeof(T) >= 2 && sizeof(T) <= 4
int foo() { }
```
The above 2 versions of foo are in fact ambiguous - the two 'sizeof(T) >= 2's are not considered the same constraint expressions, because according to the working draft, for subsumption to occur, the two atomic constraints must originate from the same source-level construct, e.g.
```
template<typename T>
concept C = sizeof(T) >= 2;
template<typename T> requires C<T>
int foo() { }
template<typename T> requires C<T> && sizeof(T) <= 4
int foo() { }
```
In the above case, the second foo is more specialized than the first.

Another reason your code wouldn't work is because subsumption does not look into requires expressions - `requires { requires has_value_type<t>; }` does not subsume `requires { requires has_value_type<t>; typename value_type_t<value_type_t<t>>; }`. You could instead wrap each separate constraint in its own requires expression like so:
```
requires { requires has_value_type<t>; }
requires { requires has_value_type<t>; } && requires { typename value_type_t<value_type_t<t>>; }
```
Then put `requires { requires has_value_type<t>; }` in its own concept.
You can drop the parameter list BTW (`requires { ... }` instead of `requires (t) { ... }`, as you aren't naming or using the t parameter)

**Comment by marehr** [comment]
cc: @h-2

**Comment by h-2** [comment]
> Another reason your code wouldn't work is because subsumption does not look into requires expressions

Wow, really, are you sure? Why did they not not take the behaviour from the TS? It was such a nice design that two concepts where treated the same when they were semantically the same, not only if they are syntactically equal.

**Comment by CaseyCarter** [comment]
> Why did they not not take the behaviour from the TS?

https://wg21.link/p0717. Consensus opinion was that constraints should be more structural and less syntactic.

**Comment by h-2** [comment]
Thanks for the link, @CaseyCarter :+1: 

I hadn't thought of the problems mentioned in the paper. In that light it makes sense to change the behaviour, of course.
